sudo: required
services:
  - docker

before_install:
  - docker build -t def-main/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true def-main/react-test npm test

after_success:
  - docker build -t def-main/multi-client ./client
  - docker build -t def-main/multi-nginx ./nginx
  - docker build -t def-main/multi-server ./server
  - docker build -t def-main/multi-worker ./worker
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #- docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  #push to docker hub
  - docker push def-main/multi-client
  - docker push def-main/multi-nginx
  - docker push def-main/multi-server
  - docker push def-main/multi-worker


